<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پخش آرایه
</font>
</h1>


In [1]:
import numpy as np
np.random.seed(1400)

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در کد زیر، با استفاده از خاصیت پخش آرایه در نامپای، دو آرایه a و b را در هم ضرب می‌کنیم و نتیجه، ضرب نظیر به نظیر عناصر آرایه‌ها می‌باشد.
</font>
</p>


In [2]:
a = np.array([0, 1, 2, 3])
b = np.array([2, 2, 2, 2])
a * b

array([0, 2, 4, 6])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در نامپای می‌توانیم با ضرب کردن یک عدد در آرایه هم به همین نتیجه برسیم.
</font>
</p>



In [3]:
2 * a

array([0, 2, 4, 6])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در کد زیر، آرایه b در محور اول کش آمده است.</font>
</p>


In [4]:
a = np.arange(12).reshape(3, 4)
print(a)
b = np.array([3, 2, 1, 0])
print(b)
a + b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[3 2 1 0]


array([[ 3,  3,  3,  3],
       [ 7,  7,  7,  7],
       [11, 11, 11, 11]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در کد زیر، آرایه b در محور دوم کش آمده است.</font>
</p>


In [5]:
b = np.array([8, 4, 0]).reshape(3, 1)
print(b)
a + b

[[8]
 [4]
 [0]]


array([[ 8,  9, 10, 11],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
این‌ بار هر دو آرایه کش آمده‌اند و همشکل شده‌اند.</font>
</p>


In [6]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4]).reshape(4, 1)
print(a)
print(b)
a * b

[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]]


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
یک آرایه دو بعدی شامل اعداد تصادفی یک تا پنج ایجاد می‌کنیم.</font>
</p>


In [7]:
a = np.random.normal(5, 1, (4, 5))
print(a)

[[5.28673734 3.38577421 2.72602328 4.40777194 5.48303679]
 [5.14370563 2.93812221 4.62113268 3.95564985 4.53204388]
 [3.05598004 4.63915843 4.15437606 4.60649393 4.87158773]
 [6.69910341 4.79489784 3.64676395 5.07856894 4.08735179]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
میانگین هر ستون را در آرایه <code>col_mean</code> میریزیم.</font>
</p>


In [8]:
col_mean = a.mean(axis=0)
print(col_mean)

[5.04638161 3.93948817 3.78707399 4.51212117 4.74350505]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
با کمک گرفتن از ویژگی پخش، میانگین هر ستون را از تک تک عناصر آن ستون کم می‌کنیم.
</p>


In [9]:
a -= col_mean
print(a)

[[ 0.24035574 -0.55371397 -1.06105071 -0.10434923  0.73953174]
 [ 0.09732402 -1.00136596  0.83405869 -0.55647132 -0.21146116]
 [-1.99040157  0.69967025  0.36730207  0.09437277  0.12808268]
 [ 1.65272181  0.85540967 -0.14031005  0.56644778 -0.65615326]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
بار دیگر میانگین هر سطر را محاسبه می‌کنیم که می‌بینید برای هر ستون تقریبا صفر است.
</p>


In [10]:
a.mean(axis=0)

array([3.33066907e-16, 3.33066907e-16, 0.00000000e+00, 1.11022302e-16,
       0.00000000e+00])