<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقایسه و منطق بولی
</font>
</h1>


In [1]:
import numpy as np

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در کد زیر، برای عناصری که مقدار آنها از ۷ کمتر است، مقدار <code>True</code> در آرایه خروجی قرار گرفته است.
</font>
</p>


In [2]:
a = np.array([2, 13, -5, -3, 19, -17])
a < 7 # سمت راست مقایسه به شکل یک آرایه (,6) با مقادیر 7 در می‌آید

array([ True, False,  True,  True, False,  True])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
این بار عناصر آرایه نظیر به نظیر با قدر مطلق خود مقایسه شده‌اند.

</font>
</p>


In [3]:
a == np.sqrt(a ** 2)  # دو سمت مقایسه می‌توانند هم‌نوع نباشند اما مقایسه‌پذیر باشند

array([ True,  True, False, False,  True, False])

In [4]:
t = np.array([[10, 12, 11, 17, 15, 11, 14],
             [13, 15, 18, 21, 19, 18, 17],
             [18, 20, 21, 19, 23, 24, 22],
             [20, 23, 19, 21, 25, 22, 21]])

In [5]:
t > 20 # خروجی یک آرایه (7 ,4) با مقادیر بولی است

array([[False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False],
       [False, False,  True, False,  True,  True,  True],
       [False,  True, False,  True,  True,  True,  True]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
با استفاده از متد <code>count_nonzero</code> تعداد عناصر غیر صفر یک آرایه نامپای برگردانده می‌شود. در پایتون، True برابر یک و False برابر صفر است. در نتیجه تعداد True ها برگردانده می‌شود.
</font>
</p>


In [6]:
np.count_nonzero(t > 20)

10

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
کد زیر، تعداد True در هر سطر را برمی‌گرداند.</font>
</p>


In [7]:
np.sum(t > 20, axis=1)

array([0, 1, 4, 5])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
تابع any یک آرایه را می گیرد و اگر یکی از عناصر True باشد، مقدار True برمی‌گرداند. در کد زیر همه عناصر t > 30 مقدار False دارند.
</font>
</p>


In [8]:
np.any(t > 30)

False

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
متد all میبیند که آیا همه عناصر True هستند یا نه. </font>
</p>


In [9]:
np.all(t >= 10)

True

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
کد زیر، تعداد عناصری که بزرگتر مساوی ۱۵ و کوچکتر مساوی ۲۰ هستند را برمی گرداند.</font>
</p>


In [10]:
np.sum((t >= 15) & (t <= 20))

12

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
کد زیر همان کار کد بالا را انجام می‌دهد. با این تفاوت که ابتدا عناصری که شرط را ندارند، انتخاب شده‌اند، سپس عناصر باقیمانده به خروجی داده شده‌اند.
</font>
</p>


In [11]:
np.sum(~((t < 15) | (t > 20)))

12